// Seed baseline matching src/data/facilities.js on the frontend, so ids line up.
export const FACILITIES = [
  // --- Nairobi, Kenya ---
  {
    id: 'ke-tlt-001',
    name: 'Kibera DC Public Toilet',
    category: 'toilet',
    image: '/facilities/toilet-1.jpg',
    area: 'Kibera, Nairobi',
    country: 'Kenya',
    lat: -1.3133,
    lng: 36.782,
    status: 'clean',
    rating: 4.2,
    ratingsCount: 58,
    hours: '5:00 AM – 10:00 PM',
    description: 'Pay-per-use toilet block with handwashing station, managed by a local CBO.',
  },
  {
    id: 'ke-tlt-002',
    name: 'Toi Market Toilet Block',
    category: 'toilet',
    image: '/facilities/toilet-2.jpg',
    area: 'Kibera, Nairobi',
    country: 'Kenya',
    lat: -1.3092,
    lng: 36.7775,
    status: 'filling',
    rating: 3.4,
    ratingsCount: 34,
    hours: '6:00 AM – 9:00 PM',
    description: 'High-traffic market toilet. Reported filling up faster than usual this week.',
  },
  {
    id: 'ke-tlt-003',
    name: 'Mukuru Kwa Njenga Community Toilet',
    category: 'toilet',
    image: '/facilities/toilet-3.jpg',
    area: 'Mukuru Slums, Nairobi',
    country: 'Kenya',
    lat: -1.3106,
    lng: 36.8767,
    status: 'broken',
    rating: 2.6,
    ratingsCount: 21,
    hours: '24 hours',
    description: 'Door lock and one cubicle broken. Reported to county sanitation office.',
  },
  {
    id: 'ke-tlt-004',
    name: 'River Road Public Convenience',
    category: 'toilet',
    image: '/facilities/toilet-1.jpg',
    area: 'River Road, Nairobi CBD',
    country: 'Kenya',
    lat: -1.2822,
    lng: 36.8267,
    status: 'clean',
    rating: 4.0,
    ratingsCount: 112,
    hours: '5:30 AM – 11:00 PM',
    description: 'Council-run facility near the matatu terminus, attendant on site.',
  },
  {
    id: 'ke-wst-001',
    name: 'Mukuru Waste Transfer Point',
    category: 'waste',
    image: '/facilities/waste-1.jpg',
    area: 'Mukuru Slums, Nairobi',
    country: 'Kenya',
    lat: -1.3084,
    lng: 36.8791,
    status: 'full',
    rating: 3.1,
    ratingsCount: 19,
    hours: 'Collection Mon/Wed/Fri',
    description: 'Communal skip. Currently overflowing — awaiting scheduled collection.',
  },
  {
    id: 'ke-wst-002',
    name: 'Kibera Soweto East Sewage Point',
    category: 'waste',
    image: '/facilities/waste-1.jpg',
    area: 'Kibera, Nairobi',
    country: 'Kenya',
    lat: -1.3151,
    lng: 36.7856,
    status: 'clean',
    rating: 3.8,
    ratingsCount: 27,
    hours: 'Collection Tue/Sat',
    description: 'Exhauster-accessible sewage disposal point serving Soweto East village.',
  },
  {
    id: 'ke-wtr-001',
    name: 'Kibera Line Saba Communal Tap',
    category: 'water',
    area: 'Kibera, Nairobi',
    country: 'Kenya',
    lat: -1.3117,
    lng: 36.7839,
    status: 'operational',
    rating: 4.4,
    ratingsCount: 76,
    hours: '5:00 AM – 8:00 PM',
    description: 'Metered communal tap connected to Nairobi Water. Reliable pressure.',
  },
  {
    id: 'ke-wtr-002',
    name: 'Mukuru Borehole #3',
    category: 'water',
    area: 'Mukuru Slums, Nairobi',
    country: 'Kenya',
    lat: -1.3061,
    lng: 36.8739,
    status: 'broken',
    rating: 2.9,
    ratingsCount: 15,
    hours: '24 hours',
    description: 'Pump motor failure reported. Community using neighbouring tap meanwhile.',
  },
  {
    id: 'ke-hlt-001',
    name: 'Kibera South Health Centre',
    category: 'health',
    area: 'Kibera, Nairobi',
    country: 'Kenya',
    lat: -1.3145,
    lng: 36.7891,
    status: 'open',
    rating: 4.1,
    ratingsCount: 89,
    hours: '8:00 AM – 5:00 PM (Mon–Sat)',
    description: 'Public health centre offering outpatient services and a small pharmacy.',
  },
  {
    id: 'ke-hlt-002',
    name: 'Mukuru Promotion Centre Clinic',
    category: 'health',
    area: 'Mukuru Slums, Nairobi',
    country: 'Kenya',
    lat: -1.3038,
    lng: 36.8759,
    status: 'open',
    rating: 4.5,
    ratingsCount: 64,
    hours: '7:30 AM – 6:00 PM (Mon–Sat)',
    description: 'Community-run clinic with maternal health and WASH-related care.',
  },
  {
    id: 'ke-hlt-003',
    name: 'River Road Pharmacy Plus',
    category: 'health',
    area: 'River Road, Nairobi CBD',
    country: 'Kenya',
    lat: -1.2836,
    lng: 36.8253,
    status: 'closed',
    rating: 3.9,
    ratingsCount: 41,
    hours: '8:00 AM – 8:00 PM (Mon–Sat)',
    description: 'Retail pharmacy, currently closed for the day.',
  },

  // --- Kampala, Uganda ---
  {
    id: 'ug-tlt-001',
    name: 'Kisenyi Public Toilet Block',
    category: 'toilet',
    image: '/facilities/toilet-2.jpg',
    area: 'Kisenyi, Kampala',
    country: 'Uganda',
    lat: 0.3103,
    lng: 32.5763,
    status: 'clean',
    rating: 4.0,
    ratingsCount: 47,
    hours: '5:00 AM – 10:00 PM',
    description: 'Fee-based facility with running water, near the main market.',
  },
  {
    id: 'ug-tlt-002',
    name: 'Nakawa Market Toilet',
    category: 'toilet',
    image: '/facilities/toilet-3.jpg',
    area: 'Nakawa, Kampala',
    country: 'Uganda',
    lat: 0.3324,
    lng: 32.6188,
    status: 'filling',
    rating: 3.2,
    ratingsCount: 22,
    hours: '6:00 AM – 9:00 PM',
    description: 'Market toilet block — pit level rising, collection requested.',
  },
  {
    id: 'ug-wst-001',
    name: 'Kisenyi Sewage Disposal Point',
    category: 'waste',
    image: '/facilities/waste-1.jpg',
    area: 'Kisenyi, Kampala',
    country: 'Uganda',
    lat: 0.3086,
    lng: 32.5788,
    status: 'full',
    rating: 2.8,
    ratingsCount: 18,
    hours: 'Collection Mon/Thu',
    description: 'Shared exhauster point serving the Kisenyi informal settlement.',
  },
  {
    id: 'ug-wtr-001',
    name: 'Makindye Borehole',
    category: 'water',
    area: 'Makindye, Kampala',
    country: 'Uganda',
    lat: 0.2874,
    lng: 32.5936,
    status: 'operational',
    rating: 4.3,
    ratingsCount: 53,
    hours: '24 hours',
    description: 'Hand-pump borehole installed by a WASH NGO in 2023, well maintained.',
  },
  {
    id: 'ug-wtr-002',
    name: 'Nakawa Communal Tap',
    category: 'water',
    area: 'Nakawa, Kampala',
    country: 'Uganda',
    lat: 0.3357,
    lng: 32.6142,
    status: 'operational',
    rating: 3.9,
    ratingsCount: 31,
    hours: '5:00 AM – 9:00 PM',
    description: 'NWSC-connected tap, moderate queueing during peak hours.',
  },
  {
    id: 'ug-hlt-001',
    name: 'Kisenyi Health Centre III',
    category: 'health',
    area: 'Kisenyi, Kampala',
    country: 'Uganda',
    lat: 0.3117,
    lng: 32.5741,
    status: 'open',
    rating: 4.2,
    ratingsCount: 97,
    hours: '8:00 AM – 5:00 PM (Mon–Fri)',
    description: 'Government health centre providing outpatient and maternity services.',
  },
  {
    id: 'ug-hlt-002',
    name: 'Makindye Family Pharmacy',
    category: 'health',
    area: 'Makindye, Kampala',
    country: 'Uganda',
    lat: 0.2851,
    lng: 32.5902,
    status: 'open',
    rating: 4.0,
    ratingsCount: 29,
    hours: '8:00 AM – 9:00 PM (Daily)',
    description: 'Neighbourhood pharmacy stocking basic WASH-related medication.',
  },

  // --- Rural sample points ---
  {
    id: 'ke-wtr-003',
    name: 'Kajiado Rural Borehole',
    category: 'water',
    area: 'Kajiado County (Rural)',
    country: 'Kenya',
    lat: -1.8524,
    lng: 36.7766,
    status: 'operational',
    rating: 4.6,
    ratingsCount: 40,
    hours: '24 hours',
    description: 'Solar-powered borehole serving several pastoralist communities.',
  },
  {
    id: 'ug-wtr-003',
    name: 'Mukono Rural Water Point',
    category: 'water',
    area: 'Mukono District (Rural)',
    country: 'Uganda',
    lat: 0.3533,
    lng: 32.7553,
    status: 'broken',
    rating: 2.4,
    ratingsCount: 12,
    hours: '24 hours',
    description: 'Protected spring — reported dry/broken by the community last week.',
  },
];
